#!/bin/sh
#
# export GIT_DIFFMERGE_VERBOSE=1 to enable logging

script_path="${0%/*}"
. "$script_path/../diff-and-merge-support"

. "$script_path/tool"
diff_args "$1" "$2" || exit $?

"$tool" /e \
        /u \
        /dl "$left_title" \
        /dr "$right_title" \
        "$left" \
        "$right"
