set encoding=utf8

" Run as VIM not VI.
set nocompatible

" Everything should be English.
language messages en_US.UTF-8
set langmenu=en_US.UTF-8

" Enable syntax highlighting.
syntax on

" Default window size
set textwidth=120

" Draw a vertical red line in column 121.
set colorcolumn=121

" Yank into and put from the Windows clipboard.
set clipboard=unnamed

" File-type highlighting and configuration.
" Run :filetype (without args) to see what you may have
" to turn on yourself, or just set them all to be sure.
filetype on
filetype plugin on
filetype indent on

set autoindent smartindent

nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

" Set the fold column, so we can use the mouse to open and close folds
set foldcolumn=2

" The width of a TAB is set to 2.
set tabstop=2
" Indents will have a width of 2.
set shiftwidth=2
" Sets the number of columns for a TAB.
set softtabstop=2

" Show line numbers.
set number

" Do not wrap lines.
set nowrap

" Show matching brackets.
set showmatch

" Bracket blinking.
set mat=5

" Always show status line.
set laststatus=2

set statusline=%<%f\ %h%y\ [%{&ff}]%m%r\ %=%-14.(%l,%c%V%)\ %P

" Mouse in all modes
set mouse=a

set history=1000
set matchtime=0
" The “Press ENTER or type command to continue” prompt is jarring and usually unnecessary. You can shorten command-line text and other info tokens with.
set shortmess=atI

" Now in the bottom right corner of the status line there will be something like: 529, 35 68%, representing line 529, column 35, about 68% of the way to the end.
set ruler
set showcmd

" When the cursor is moved outside the viewport of the current window, the buffer is scrolled by a single line. Setting the option below will start the scrolling three lines before the border, keeping more context around where you’re working.
set scrolloff=3
set sidescroll=1
set sidescrolloff=3

" A running gvim will always have a window title, but when vim is run within an xterm, by default it inherits the terminal’s current title.
set title

" Search options
" Highlight search terms
set hlsearch
set incsearch
" These two options, when set together, will make /-style searches case-sensitive only if there is a capital letter in the search expression. *-style searches continue to be consistently case-sensitive.
set ignorecase
set smartcase

" Blink if there is an error
set visualbell
set noerrorbells

" Make backspace delete lots of things
set backspace=indent,eol,start

" Auto-backup files and .swp files don't go to pwd
set backupdir=$TEMP,.
set directory=$TEMP,.

" Allow switching edited buffers without saving
set hidden

set background=light

" The <Leader> character is your own personal modifier key, as g is Vim’s modifier key (when compared to vi). The default leader is \, but this isn’t located standardly on all keyboards and requires a pinky stretch in any case
let mapleader = ","

" Quick timeouts on key combinations.
set timeoutlen=300

" The following will make tabs and trailing spaces visible when requested.
set listchars=tab:>-,space:·,trail:~,eol:¶,precedes:«,extends:»
" ,s shows trailing whitespace.
nmap <silent> <leader>s :set nolist!<CR>

" Fix command typos (stolen from Adam Katz)
nmap ; :

" These are very similar keys. Typing 'a will jump to the line in the current file marked with ma. However, `a  will jump to the line and column marked with ma!
" ` is more useful than ' but less accessible.
nnoremap ' `
nnoremap ` '

" Buffer management
nmap <C-h> :bp<CR>
nmap <C-l> :bn<CR>
nmap <C-d> :bw<CR>
vmap <C-d> :bw<CR>

" Toggle highlighting
nmap <silent> <C-n> :silent :nohlsearch<CR>

" Scroll faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
vnoremap <C-e> 3<C-e>
vnoremap <C-y> 3<C-y>

" Bash-like filename completion
set wildmenu
set wildmode=list:longest
set wildignore=*.o

autocmd Filetype yaml set tabstop=2 shiftwidth=2 softtabstop=2 expandtab

" Automatically cd into the directory of the edited file.
" alternatively: autocmd BufEnter * cd %:p:h
if exists("&autochdir")
  set autochdir
endif

" Buffers - next/previous: F12, Shift-F12.
nnoremap <silent> <F12> :bn<CR>
nnoremap <silent> <S-F12> :bp<CR>
