# Tap homebrew/dupes in order to be able to install addtional utilities below
# that are also provided with macOS.
tap 'homebrew/dupes'

# GNU utilities.
brew 'binutils'
brew 'coreutils'
brew 'diffutils'
brew 'file-formula'
brew 'findutils', args: %w(with-default-names)
brew 'gawk'
brew 'gnu-getopt'
brew 'gnu-indent', args: %w(with-default-names)
brew 'gnu-sed', args: %w(with-default-names)
brew 'gnu-tar', args: %w(with-default-names)
brew 'gnu-which', args: %w(with-default-names)
brew 'gnutls'
brew 'gpatch'
brew 'grep', args: %w(with-default-names)
brew 'gzip'
brew 'less'
brew 'make'
brew 'rsync'
brew 'unzip'
brew 'watch'

brew 'mas'

# Apps without topic directories.
cask 'android-file-transfer'
cask 'dropbox'
cask 'double-commander'
cask 'flux'
cask 'google-chrome'
cask 'google-hangouts'
cask 'istat-menus'
cask 'karabiner-elements'
cask 'skype'
