# Allows to install updates automatically.
tap 'domt4/autoupdate'

# GNU utilities.
brew 'binutils'
brew 'coreutils'
brew 'diffutils'
brew 'dos2unix'
brew 'file-formula'
brew 'findutils'
brew 'gawk'
brew 'gnu-getopt'
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-which'
brew 'gnutls'
brew 'gpatch'
brew 'grep'
brew 'gzip'
brew 'make'
brew 'rsync'
brew 'tree'
brew 'unzip'
brew 'watch'

# QuickLook plugins, https://github.com/sindresorhus/quick-look-plugins
cask 'betterzip'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-json'
cask 'quicklookase'
cask 'suspicious-package'
cask 'webpquicklook'

# FUSE.
cask 'osxfuse'
brew 'sshfs'

# Apps without topic directories.
brew 'curl'
brew 'httpie'
brew 'imagemagick'
brew 'jid'
brew 'm-cli'
brew 'ncdu'
brew 'nmap'
brew 'p7zip'
brew 'shellcheck'
brew 'shfmt'
brew 'speedtest_cli'
brew 'testssl'
brew 'wakeonlan'
brew 'webkit2png'
brew 'xz'

cask 'android-file-transfer'
cask 'anydesk'
cask 'atext'
cask 'authy'
cask 'bartender'
cask 'banking-4'
cask 'bettertouchtool'
cask 'boom-3d'
cask 'cleanmymac'
cask 'dash'
cask 'dotnet-sdk'
cask 'double-commander'
cask 'dropbox'
cask 'evernote'
cask 'flux'
cask 'google-chrome'
cask 'google-hangouts'
cask 'hosts'
cask 'hyperdock'
cask 'hyperswitch'
cask 'istat-menus'
cask 'java'
cask 'jetbrains-toolbox'
cask 'kap'
cask 'key-codes'
cask 'keyboardcleantool'
cask 'launchcontrol'
cask 'lumen'
cask 'macdown'
cask 'nextcloud'
cask 'paste'
cask 'popclip'
cask 'postman'
cask 'roboform'
cask 'skype'
cask 'symboliclinker'
cask 'teamviewer'
cask 'xnviewmp'

# Apps from the Mac App Store.
mas 'Better', id: 1_121_192_229
mas 'CleanMyDrive', id: 523_620_159
mas 'EasyRes', id: 688_211_836
mas 'FruitJuice', id: 671_736_912
mas 'Microsoft Remote Desktop', id: 1_295_203_466
mas 'Monosnap', id: 540_348_655
mas 'Moom', id: 419_330_170
mas 'PCalc', id: 403_504_866
mas 'Reeder', id: 880_001_334
mas 'Spark', id: 1_176_895_641
mas 'Trello', id: 1_278_508_951
mas 'Tweetbot 3', id: 1_384_080_005
mas 'WhatsApp', id: 1_147_396_723

# vim: set ft=ruby ts=2 sw=2 et:
