#!/bin/sh
#
# export GIT_DIFFMERGE_VERBOSE=1 to enable logging

script_path="${0%/*}"
. "$script_path/../diff-and-merge-support"

. "$script_path/tool"
merge_args "$1" "$2" "$3" "$4" || exit $?

"$tool" --merge \
        --result="$result" \
        "$local" \
        "$base" \
        "$remote" \
        --title1="Mine" \
        --title2="Merged: $4" \
        --title3="Theirs"
