#!/bin/sh
#
# export GIT_DIFFMERGE_VERBOSE=1 to enable logging

script_path="${0%/*}"
. "$script_path/../diff-and-merge-support"

. "$script_path/tool"
merge_args "$1" "$2" "$3" "$4" || exit $?

"$mergetool" -b="$base" \
             -d="$local" \
             -s="$remote" \
             -r="$result" \
             -l=csharp \
             -emt="mergetool.exe \
                   -b=\"@basefile\" \
                   -bn=\"@basesymbolic\" \
                   -s=\"@sourcefile\" \
                   -sn=\"@sourcesymbolic\" \
                   -d=\"@destinationfile\" \
                   -dn=\"@destinationsymbolic\" \
                   -r=\"@output\" \
                   -t=\"@filetype\" \
                   -i=\"@comparationmethod\" \
                   -e=\"@fileencoding\" \
                   -edt=\"mergetool.exe \
                   -s=\"@sourcefile\" \
                   -sn=\"@sourcesymbolic\" \
                   -d=\"@destinationfile\" \
                   -dn=\"@destinationsymbolic\" \
                   -t=\"@filetype\" \
                   -i=\"@comparationmethod\" \
                   -e=\"@fileencoding\""
