#!/bin/sh
#
# export GIT_DIFFMERGE_VERBOSE=1 to enable logging

script_path="${0%/*}"
. "$script_path/../diff-and-merge-support"

. "$script_path/tool"
diff_args "$1" "$2" || exit $?

"$tool" "$left" "$right"
