#!/usr/bin/env bash

set -euo pipefail

album_id="${1?Need album ID}"
album="${2?Need album}"
artpath="${3?Need album artpath}"

green='\e[1;32m'
yellow='\e[1;33m'
blue='\e[1;34m'
reset='\e[0m'

# shellcheck disable=SC2016
mapfile -t -n 1 addeds < <(beet info --library --format '$added' "album_id:${album_id}")
added="${addeds[0]-}"

if [[ -z "$added" ]]; then
  >&2 printf 'No added timestamp for %s\n' "$album"
  exit 1
fi

ts="$(date -d "$added" +%s)"

printf '%b%s%b = %b%s%b for %b%s%b\n' \
       "$green" "$added" "$reset" \
       "$yellow" "$ts" "$reset" \
       "$blue" "$artpath" "$reset"

touch -m --date "@$ts" -- "$artpath"
