ZSH_VERBOSE=true

# Path to zsh files.
ZSH="$HOME/.zsh"

# Prepend our function path and remove duplicates.
typeset -Ua fpath
fpath=("$ZSH/functions" "$ZSH/functions/startup" $fpath)

# Autoload all functions from our functions path. Just execute the function,
# no need to autoload <function> before.
# See http://zsh.sourceforge.net/FAQ/zshfaq03.html, section 3.11.
autoload -Uz $ZSH/functions/*(:t) $ZSH/functions/startup/*(:t)

# Load color support.
source "$ZSH/lib/colors.zsh"

verbose Loading $fg[green]zshenv$reset_color
