paths=($HOME/bin $HOME/bin/*/(/) $PATH)
PATH=${(j.:.)paths}

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.zsh

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

export DISPLAY=localhost:0.0
