verbose Loading $fg[green]zshrc$reset_color

ZPLUG_HOME=$HOME/.cache/zplug
if [[ ! -d $ZPLUG_HOME ]]; then
  verbose Downloading $fg[cyan]zplug$reset_color to $fg[green]$ZPLUG_HOME$reset_color
  mkdir --parents "$ZPLUG_HOME"
  wget -O "$ZPLUG_HOME/zplug" git.io/zplug

  verbose Loading $fg[cyan]zplug$reset_color
  source "$ZPLUG_HOME/zplug"

  zplug update --self
else
  verbose Loading $fg[cyan]zplug$reset_color
  source "$ZPLUG_HOME/zplug"
fi

zplug "~/.zsh/config", from:local, nice:-20
zplug "~/.zsh/themes", from:local, of:"agross.zsh-theme"
zplug "~/.zsh/lib", from:local

zplug "b4b4r07/zplug"
zplug "plugins/ssh-agent", from:oh-my-zsh
zplug "bobthecow/git-flow-completion"
zplug "rhysd/zsh-bundle-exec", if:"which bundle"

zplug "zsh-users/zsh-syntax-highlighting", nice:10

# Install plugins if there are plugins that have not been installed.
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo
    zplug install
  fi
fi

# Source and add to the PATH.
zplug load --verbose
