#!/usr/bin/env bash

music="${1?Need music directory}"

dir-date-from-newest-file() {
  local dir red green reset

  dir="${1?Need directory}"
  red='\e[1;31m'
  green='\e[1;32m'
  blue='\e[1;34m'
  reset='\e[0m'

  newest="$(find "$dir" \
                 -mindepth 1 \
                 -type f \
                 -exec stat -c '%Y %n' {} \+ |
              sort -n |
              cut -d' ' -f 2- |
              tail -n 1)"

  if [[ -n "$newest" ]]; then
    printf '%b%s%b: %b%s/%b%s\n' \
           "$green" "$(stat -c '%.10y' "$newest")" "$reset" \
           "$blue" "${dir##*/}" "$reset" \
           "${newest##*/}"

    touch -r "$newest" -- "$dir"
  else
    printf "%bNo newest file%b: %s\n" "$red" "$reset" "$dir"
    exit 1
  fi
}

export -f dir-date-from-newest-file

find "$music" \
     -mindepth 1 \
     -type d \
     -print0 |
  sort -z |
  xargs -0 -I {} bash -c 'dir-date-from-newest-file "{}"'
