# Loaded for login shells only, i.e. not for screen sessions.

verbose Loading $fg[green]zprofile$reset_color

local profile
for profile in $DOTFILES/**/zprofile.zsh(N); do
  source $profile
done

# vim: set ft=zsh ts=2 sw=2 et:
