# Loaded for all shells.

# ZSH_VERBOSE=true enables logging.
# ZSH_VERBOSE=true

# Path to dotfiles.
typeset -xr DOTFILES="$HOME/.dotfiles"

# Prepend our startup function path and remove duplicates.
typeset -Ua fpath
fpath=("$DOTFILES/zsh/functions/startup" $fpath)
autoload -Uz $DOTFILES/zsh/functions/startup/*(:t)

# Language settings: This variable determines the locale category for any
# category not specifically selected via a variable starting with `LC_'.
export LANG=en_US.UTF-8

# Load color support.
autoload -U colors && colors

# https://github.com/zplug/zplug/issues/332
# verbose Loaded $fg[green]zshenv$reset_color

# vim:set filetype=sh:
