# If not running interactively, don't do anything.
[[ "$-" != *i* ]] && return

# Use case-insensitive filename globbing.
shopt -s nocaseglob

# When changing directory small typos can be ignored by bash
# for example, cd /vr/lgo/apaache would find /var/log/apache.
shopt -s cdspell

# Don't put duplicate lines in the history.
export HISTCONTROL=ignoredups

# Ignore some controlling instructions.
export HISTIGNORE="[   ]*:&:bg:fg:exit"

# Whenever displaying the prompt, write the previous line to disk.
export PROMPT_COMMAND='history -a'

alias ls='ls --color=auto -l --all --human-readable'

alias g=git
_completion_loader git
complete -o default -o nospace -F _git g
