#!/usr/bin/env bash

set -euo pipefail

ligaturizer=https://github.com/rojiani/Ligaturizer.git
meslo_repo=andreberg/Meslo-Font
meslo_style='Meslo LGS'

dir="$(mktemp --directory)"

pushd "$dir" > /dev/null

git clone --depth 1 "$ligaturizer" "$dir"
rm -rf input-fonts/* output-fonts/*

url="$(curl --fail \
           --silent \
           --location \
           https://api.github.com/repos/$meslo_repo/tags |
         sed --silent --regexp-extended 's/\s+"tarball_url": "(.+)".*/\1/p' |
         head --lines 1)"
tag="${url##*/}"

printf 'Tag: %s URL: %s\n' "$tag" "$url"
curl --fail \
     --silent \
     --location \
     "$url" |
  tar xzv |
  grep "${meslo_style%?} $tag" |
  xargs -d '\n' unzip -j -d input-fonts

if ! brew list fontforge > /dev/null; then
  brew install fontforge
fi

make

cp --verbose output-fonts/Liga${meslo_style/ /}*.ttf ~/Library/Fonts

popd > /dev/null
