#!/bin/sh
#
# export GIT_DIFFMERGE_VERBOSE=1 to enable logging

script_path="${0%/*}"
. "$script_path/diff-and-merge-support"

tool="$(tool_path "/c/Tools/Beyond Compare/BComp.exe" \
                  "bcompare" \
                  "/Applications/Beyond Compare.app/Contents/MacOS/bcomp")" || exit $?

op="${1?Need operation (diff or merge) as the first argument}"
shift

case "$op" in
  diff)
    diff_args "$1" "$2" || exit $?

    "$tool" -solo \
            -readonly \
            "$left" \
            "$right" \
            -title1="$left_title" \
            -title2="$right_title" \
            > /dev/null 2>&1
    ;;

  merge)
    merge_args "$1" "$2" "$3" "$4" || exit $?

    "$tool" -solo \
            -automerge \
            -reviewconflicts \
            "$local" \
            "$remote" \
            "$base" \
            "$result" \
            -lefttitle="Ours" \
            -centertitle="Base" \
            -righttitle="Theirs" \
            -outputtitle="Merged: $4" \
            > /dev/null 2>&1
    ;;

  *)
    printf "Unknown operation: $op\n" >&2
    exit 1
    ;;
esac
