#!/bin/sh
#
# export GIT_DIFFMERGE_VERBOSE=1 to enable logging

script_path="${0%/*}"
. "$script_path/diff-and-merge-support"

tool="$(tool_path "/c/Tools/DiffMerge/diffmerge.exe" \
                  "diffmerge" \
                  "/Applications/DiffMerge.app/Contents/Resources/diffmerge.sh")" || exit $?

op="${1?Need operation (diff or merge) as the first argument}"
shift

case "$op" in
  diff)
    diff_args "$1" "$2" || exit $?

    "$tool" "$left" \
            "$right" \
            --title1="$left_title" \
            --title2="$right_title"
    ;;

  merge)
    merge_args "$1" "$2" "$3" "$4" || exit $?

    "$tool" --merge \
            --result="$result" \
            "$local" \
            "$base" \
            "$remote" \
            --title1="Mine" \
            --title2="Merged: $4" \
            --title3="Theirs"
    ;;

  *)
    printf "Unknown operation: $op\n" >&2
    exit 1
    ;;
esac
