#!/bin/sh
#
# export GIT_DIFFMERGE_VERBOSE=1 to enable logging

script_path="${0%/*}"
. "$script_path/diff-and-merge-support"

tool="$(tool_path '/c/Tools/P4Merge/p4merge.exe' \
                  '/mnt/c/Tools/P4Merge/p4merge.exe' \
                  'p4merge' \
                  '/Applications/p4merge.app/Contents/Resources/launchp4merge')" || exit $?

op="${1?Need operation (diff or merge) as the first argument}"
shift

case "$op" in
  diff)
    diff_args "$1" "$2" || exit $?

    exec "$tool" -nl "$left_title" \
                 -nr "$right_title" \
                 "$left" \
                 "$right"
    ;;

  merge)
    merge_args "$1" "$2" "$3" "$4" || exit $?

    exec "$tool" -nl "Ours: $local_desc" \
                 -nb 'Base' \
                 -nr "Theirs: $remote_desc" \
                 -nm "Merged: $4" \
                 "$base" \
                 "$local" \
                 "$remote" \
                 "$result"
    ;;

  *)
    printf 'Unknown operation: %s\n' "$op" >&2
    exit 1
    ;;
esac
